platform :ios, '11.0'

target 'NYtimes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireImage', '~> 3.5'
  pod 'Hero', '~> 1.4'

  target 'NYtimesTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYtimesUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
