platform :ios, '11.0'

target 'NYtimes' do
  pod 'Alamofire', '~> 4.8'
  pod 'AlamofireImage', '~> 3.5'
  pod 'Hero', '~> 1.4'

  target 'NYtimesTests' do
    inherit! :search_paths
  end

  target 'NYtimesUITests' do
    inherit! :search_paths
  end

end
